name: 'lar-simp-dok'

services:

  nginx:
    image: 'nginx:alpine'
    volumes:
      - '..:/var/www/html' # To serve static files, change to: - './public:/var/www/html'?
      - './containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8888:80'

  php-fpm:
    build: ./containers/php-fpm
    volumes:
      - '..:/var/www/html'
#      - './containers/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
    
  mysql:
    image: 'mysql:8.0'
    volumes:
      - './containers/mysql/mysql-volume/:/var/lib/mysql'
    ports:
      - '32004:3306'
    #env_file: './docker/.env'
    environment:
      - MYSQL_ROOT_PASSWORD=myapp_mysql_root_pass
      - MYSQL_DATABASE=myapp_db
      - MYSQL_USER=myapp_dba
      - MYSQL_PASSWORD=myapp_dba_pass